name: VanillaMinimaps
description: Fully vanilla minimaps, without any mods.
author: JNNGL/wilburforce83
version: '${pluginVersion}'
website: https://github.com/wilburforce83/VanillaMinimaps-Next
main: com.jnngl.vanillaminimaps.VanillaMinimaps
api-version: '1.21'
commands:
  minimap:
    description: Controls VanillaMinimaps.
    usage: /minimap <enable|disable|position|marker|fullscreen>
